configury: don't build ChangeLog outside git
* Makefile.am (GL_GEN): Test the .git exists and exit if not.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -82,16 +82,18 @@ install-data-hook:
 	test `id -u` -ne 0 || systemctl daemon-reload
 
 GL_GEN_BIN = gitlog-to-changelog
-GL_GEN = $(SHELL) $(top_srcdir)/$(config_aux_dir)/missing --run \
-	 $(GL_GEN_BIN) --format='%s%n%n%b%n' --since 2013-01-01 > ChangeLog ; \
-	 rc=$$? ; \
-	 if test $$rc -eq 127; then \
-	   if test x"$$IGNORE_CHANGELOG" != xyes; then \
-	     echo >&2 "ERROR: Get the $(GL_GEN_BIN) or ignore ChangeLog by IGNORE_CHANGELOG=yes" ; \
-	     exit 1 ; \
-	   fi ; \
-	 else \
-	   test $$rc -eq 0 ; \
+GL_GEN = if test -d .git; then \
+	   $(SHELL) $(top_srcdir)/$(config_aux_dir)/missing --run \
+	   $(GL_GEN_BIN) --format='%s%n%n%b%n' --since 2013-01-01 > ChangeLog ; \
+	   rc=$$? ; \
+	   if test $$rc -eq 127; then \
+	     if test x"$$IGNORE_CHANGELOG" != xyes; then \
+	       echo >&2 "ERROR: Get the $(GL_GEN_BIN) or ignore ChangeLog by IGNORE_CHANGELOG=yes" ; \
+	       exit 1 ; \
+	     fi ; \
+	   else \
+	     test $$rc -eq 0 ; \
+	   fi \
 	 fi
 
 .PHONY: ChangeLog
